version: "2"
services:
  restex:
    container_name: "restex-express-app"
    image: sunilmore690/restex-mongo
    restart: always 
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb/restex_demo
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017